### ISSUE TITLE
Ignore `node_modules` by default

### ISSUE THREAD

**Issue by eventualbuddha** [square/babel-codemod#113]
Maybe should be customizable, maybe not.

**Comment by rwjblue** [comment]
I think perhaps changing this area to use `globby` instead of `glob` would allow us to ignore all `.gitignore`d files by default. 

https://github.com/square/babel-codemod/blob/00ae5984e1b2ca2fac923011ce16157a29b12b39/src/Options.ts#L135-L139

What do you think?

**Comment by eventualbuddha** [comment]
That's a good suggestion. Thanks, @rwjblue!
