### ISSUE TITLE
[Proposal] programmatic use

### ISSUE THREAD

**Issue by nyrosmith** [square/babel-codemod#122]
How about separating the CLI part so babel-codemod can be easily used via programmatic interface?
That would ease creating tools based on this fantastic project

**Comment by nyrosmith** [comment]
Closing because of no response

**Comment by eventualbuddha** [comment]
I know it's been a really long time, but for anyone else who stumbles upon this I've started splitting the functionality into multiple packages. You can now use [`@codemod/core`](https://github.com/codemod-js/codemod/tree/master/packages/core) and [`@codemod/parser`](https://github.com/codemod-js/codemod/tree/master/packages/parser) separately.
