### ISSUE TITLE
support working with .ts files

### ISSUE THREAD

**Issue by MagicDuck** [square/babel-codemod#137]
So there's word on the web that babel7 now supports parsing typescript and recast has been modified to work with it. Apparently, `jscodemod --parser babylon` will now apply transforms on `.ts` files (https://github.com/facebook/jscodeshift/issues/180#issuecomment-389154693). It would be cool for `babel-codemod` to be able to handle `.ts` files as well. because it's my goto tool for running codemods now 😸. This is especially handy for cases where you have codebases in transition, with lots of old legacy in `.js` and newer legacy in `.ts` 😁 
I am not sure how much work would be necessary to enable this or how feasible it is. As always though, I greatly appreciate your time.

**Comment by eventualbuddha** [comment]
@MagicDuck thanks for the suggestion! Here you go: #139. Please try it out and let me know if you encounter any issues :smile:

**Comment by MagicDuck** [comment]
Wow thanks @eventualbuddha! I will try it tomorrow!

**Comment by MagicDuck** [comment]
@eventualbuddha  works as expected. You is awesome! 🎆
