### ISSUE TITLE
How to use proposal plugins?

### ISSUE THREAD

**Issue by rainboxx** [square/babel-codemod#158]
We're using `babel-plugin-proposal-optional-chaining` in one of our projects. When running a codemode we get the error

> Support for the experimental syntax 'optionalChaining' isn't currently enabled

along with a message from babel:

> Add @babel/plugin-proposal-optional-chaining (https://git.io/vb4Sk) to the 'plugins' section of your Babel config to enable transformation.

However, we have a local `.babelrc` with the plugin defined. Adding `--find-babel-config` didn't help.

Any hints to how to solve this issue? Thanks in advance!

**Comment by rainboxx** [comment]
Sorry, opened in wrong repo 😞

**Comment by eventualbuddha** [comment]
This seems like the right repo... Did you get this figured out?

**Comment by rainboxx** [comment]
@eventualbuddha It actually was the wrong repo (or at least missing more information about our use case) because I was using an already existing codemod which didn't had optional chaining. I figured it out, reason it didn't work was PEBCAK :wink:.
