### ISSUE TITLE
Import declarations not transforming properly

### ISSUE THREAD

**Issue by zelaznik** [square/babel-codemod#169]
# Summary:
- The codemod fails to transform the import declarations properly when operating on lots of files.
- It works just fine when the code mod is run only one file at a time.
- I'm using version 2.0.6

# Details

I'm writing a series of babel code mod transformations to get rid of depreciated jQuery methods in our Ember app.  When the code is transformed somewhere in the file, we need to make sure to import the proper methods at the top of the file.  Here's an example of the transformation I built:

```js
import { click } from 'ember-native-dom-helpers'
```

becomes:

```js
import { click, findAll } from 'ember-native-dom-helpers'
```

This transformation works just fine in AST explorer, such as in this link:

https://astexplorer.net/#/gist/f910710bddc949b00b5c3a062943a79f/b5c8398618a0ea6df8f027661575206509d36c5f

When I try to run the code-mod locally, however, many of the import declarations don't get converted properly.  Here's the script that I ran in our internal ember application.

```sh
codemod tests/acceptance/ --remote-plugin "https://astexplorer.net/#/gist/f910710bddc949b00b5c3a062943a79f/b5c8398618a0ea6df8f027661575206509d36c5f"
```

Once I run a diff on the code, it shows the import statements unaltered.

```diff
+++ b/facesheet/tests/acceptance/scheduling/admin-locations-schedule-test.js
@@ -64,9 +64,7 @@ describe('Acceptance \| hello world page', function() {
   it('lists location displayName', async function() {
     await visit('some_internal_url');

-    const locationNames = find('.our-selector-name')
-      .map((i, el) => el.text)
-      .get();
+    const locationNames = findAll('.eng-location-schedule-link').map(el => el.textContent);
     expect(locationNames).to.include.members(['Nest', 'Dartmouth']);
   });
```

But, when I run the codemod on that single file alone, everything works fine, everything works as expected.

```sh
codemod tests/acceptance/hello-world-test.js --remote-plugin "https://astexplorer.net/#/gist/f910710bddc949b00b5c3a062943a79f/b5c8398618a0ea6df8f027661575206509d36c5f"
```

Here's the git diff when the codemod is run one file at a time:

```diff
-import { find as findNativeDOM, waitUntil } from 'ember-native-dom-helpers';
+import { find as findNativeDOM, waitUntil, findAll } from 'ember-native-dom-helpers';

 describe('Acceptance | hello world page', function() {
   let application;
@@ -64,9 +64,7 @@ describe('Acceptance | hello world page', function() {
   it('lists location displayName', async function() {
     await visit('some_internal_url');

-    const locationNames = find('.our-selector-name')
-      .map((i, el) => el.text)
-      .get();
+    const locationNames = findAll('.our-selector-name').map(el => el.textContent);
     expect(locationNames).to.include.members(['Nest', 'Dartmouth']);
   });
```

Let me know if you need any more details from me.  Despite this issue, this babel code-mod tool has been immensely useful, to thank you a thousand times for making it open source!

- Steve Z.

**Comment by eventualbuddha** [comment]
Thanks for the detailed report! It's much easier to figure out what's going on when an issue is created with lots of information. I can almost guarantee that the issue is due to unintended state preservation between files in your codemod. Specifically, the block of variable declarations at the top:

```js
  let matchFound = false;
  let nativeDomHelpersImports = [];
  let importedFindAll;
  let findAllName = "findAll";
  let declarators = [];
```

The easiest way to fix this is to add an `enter` hook to your `Program` visitor and reset them all. If this turns out to not be the issue, please feel free to comment again and I'll see what I can do to help out. Best of luck with getting rid of jQuery! We've been doing the same in some of our Ember codebases at Square. cc @edruder
