### ISSUE TITLE
Provide an option to parse a file as a script.

### ISSUE THREAD

**Issue by cameron-martin** [square/babel-codemod#175]
I am creating a codemod for converting a _script_ into a _module_ while retaining the same behaviour - the idea is to use it to integrate legacy scripts into a webpack build.

However, the issue is that the [`sourceType` option to babel's parser is hardcoded to `'module'`](https://github.com/square/babel-codemod/blob/672b81b229421e6acdcec01de0edaa23ee2dddd1/src/AllSyntaxPlugin.ts#L35) in this library, when I need it to parsed as a script.

Could this be added as an option to the CLI?

**Comment by eventualbuddha** [comment]
Thanks for the suggestion! This should hopefully just work as-is if you update to v2.1.0, but you also have the option to specify the source type if you have to.

**Comment by cameron-martin** [comment]
Thanks for this!
