### ISSUE TITLE
Allow prettier(-eslint) for the output

### ISSUE THREAD

**Issue by kentcdodds** [square/babel-codemod#20]
Based on [this](https://github.com/prettier/prettier/issues/1020#issuecomment-287315441). Specifically, I think that both `prettier` and `prettier-eslint` should be supported. Many folks would benefit from the eslint integration even if they're not using prettier at all.

**Comment by benjamn** [comment]
Won't prettier reformat the whole file, though? Would it be an optional post-processing step, then?

**Comment by kentcdodds** [comment]
True. Now that I think of it, it may be better to just expose a mechanism for general post-processing of all changed files (not specific to any tool like prettier). 🤔

**Comment by eventualbuddha** [comment]
Sounds reasonable to me. Suggestions for API?

**Comment by kentcdodds** [comment]
Maybe add a `--postprocess` flag?

```
codemod --plugin ./my-plugin.js src/ --postprocess "prettier-eslint --write"
```

```
codemod --plugin ./my-plugin.js src/ --postprocess "prettier --single-quote --write"
```

```
codemod --plugin ./my-plugin.js src/ --postprocess ./my-postprocessor
```

**Comment by benjamn** [comment]
If a command-line option really makes it easier to run subsequent commands, this proposal might make sense. The thing about post-processing steps, though, is that the pre-processing tool may not need to know about them at all. Just run two commands?

**Comment by kentcdodds** [comment]
Yeah, two commands is fine. The only thing is that I only want to run the post-processor on files which were changed as a result of the codemod and not over my entire codebase.

**Comment by kentcdodds** [comment]
I should note that this is hypothetical and that may end the discussion right there. For my specific use-case, I could just run the codemod, then rerun prettier-eslint on my whole project and everything would be fine. So maybe it's not necessary to add this 🙃

**Comment by benjamn** [comment]
Hmm, I see what you mean. What if the `codemod` command printed the names of changed files to STDOUT, so that you could easily process them with another command? Any other output could go to STDERR.

**Comment by kentcdodds** [comment]
Yeah, I'd considered that. Could probably make that work + some fancy shell stuff. Probably best to have a flag for that. But I'm on board :+1:

**Comment by eventualbuddha** [comment]
This could be as simple as adding a `--no-summary` flag that omits the summary at the end and then you could pipe the names to whatever. Does that sound reasonable? Any errors that occur go to stderr anyway so you wouldn't have to worry about them.

**Comment by kentcdodds** [comment]
Sounds great! That and an example in the docs would be awesome.

**Comment by kentcdodds** [comment]
I honestly don't care too much about this anymore so I'm going to go ahead and close this issue. Feel free to add the note in the docs if you like though :)

**Comment by eventualbuddha** [comment]
Re-opening since I now think something like this might be a good idea. The reason I've changed my mind is that I've found it kind of annoying to have to string the commands together in a reasonable way.

**Comment by kentcdodds** [comment]
Awesome! Thanks!
