### ISSUE TITLE
Allow easier development of codemods

### ISSUE THREAD

**Issue by eventualbuddha** [square/babel-codemod#29]
Extracted from #25, specifically see https://github.com/square/babel-codemod/pull/25#issuecomment-309765375.

Personally, I'd like to see options for easily testing plugins written in both babel and TypeScript.

**Comment by mcMickJuice** [comment]
should we have two issues here, one for babel setting, one for typescript?  the PR i just attached only addresses babel transpile option

**Comment by mcMickJuice** [comment]
Should we close this issue since we have:
* PR merged for babel - https://github.com/square/babel-codemod/pull/31
* pending PR for typescript and a separate issue, https://github.com/square/babel-codemod/pull/57 and https://github.com/square/babel-codemod/issues/51 respectively

**Comment by eventualbuddha** [comment]
Yeah, I think this is covered by the other issues now.
