### ISSUE TITLE
CLI Tests failing on Windows

### ISSUE THREAD

**Issue by mcMickJuice** [square/babel-codemod#32]
The cli tests are failing on my windows machine:

version of node: 8.0.0
windows 10 pro

* ENOENT errors related to this call in runCodemodCLI:
`let child = execFile(join(__dirname, '../bin/codemod'), args);`
* infinite loop occurring in tests where `createTemporaryFile` is called

The former is probably related to spawn issues with execFile on windows...the latter, i have no idea.

Tests are passing in CI env based on my recent PR though, that's why I think this is windows specific...or just my machine?

**Comment by eventualbuddha** [comment]
Did this ever get fixed or is it still an issue for you?

**Comment by mcMickJuice** [comment]
Yea, this was still happening. Opened a PR against this issue to fix.
