### ISSUE TITLE
Babel-core: make it a peerDep

### ISSUE THREAD

**Issue by hzoo** [square/babel-codemod#41]
So that you can use a different version (v7)

I guess the only issue is how that would work with `npx` or a global install..

**Comment by eventualbuddha** [comment]
Isn't v7 a fairly different API?

**Comment by hzoo** [comment]
Uh the api meaning like babel-core stuff is basically the same? If you mean the AST, some things are a little different but those are for the experimental nodes/proposals anyway. But yeah not sure about how this will work with npx anyway

**Comment by eventualbuddha** [comment]
codemod now uses babel 7.x, so I'm going to close this.
