### ISSUE TITLE
{type: Noop} does not match type string

### ISSUE THREAD

**Issue by MagicDuck** [square/babel-codemod#43]
I see this error when I run a babel plugin that uses `t.noop()` to create a node. I am assuming the version of babel needs to be updated...

**Comment by mcMickJuice** [comment]
Would you please post your plugin code here so we can try to repro?

**Comment by MagicDuck** [comment]
hi @mcMickJuice,

Thanks for looking into this issue and thanks for the awesome tool. I feel so much power running it over 2000 legacy js files and watching it change them, muhahaha :)

Regarding `t.noop()`, here's the AST Explorer saved session that also exhibits the behaviour: https://astexplorer.net/#/gist/f414b2747916f09125b4a467e5b6ae19/latest

When I ran this type of stuff manually/locally using `babel.transform()` with babel-core@6.26.0, I remember it working correctly.

The babel docs also document `t.noop`: https://babeljs.io/docs/core-packages/babel-types/#apinoop

**Comment by mcMickJuice** [comment]
all props go to @eventualbuddha as he is the project creator and maintainer. I'm just helping out.

I can look at this sometime this week and get back to you. Hopefully its just a version issue.

**Comment by eventualbuddha** [comment]
@MagicDuck codemod now uses babel 7.x, but this problem seems to still exist. I think it's actually a recast issue as the assertion that fails is in recast. I think recast needs to be taught about `Noop` nodes. @benjamn, what do you think?

```
Encountered an error while processing test.js:
Error: {type: Noop} does not match type string
    at Type.Tp.assert (/Users/donovan/src/babel-codemod/node_modules/ast-types/lib/types.js:60:19)
    at /Users/donovan/src/babel-codemod/node_modules/recast/lib/printer.js:1698:22
    at FastPath.each (/Users/donovan/src/babel-codemod/node_modules/recast/lib/fast-path.js:145:7)
    at printStatementSequence (/Users/donovan/src/babel-codemod/node_modules/recast/lib/printer.js:1670:10)
    at /Users/donovan/src/babel-codemod/node_modules/recast/lib/printer.js:544:20
    at FastPath.call (/Users/donovan/src/babel-codemod/node_modules/recast/lib/fast-path.js:119:16)
    at genericPrintNoParens (/Users/donovan/src/babel-codemod/node_modules/recast/lib/printer.js:543:26)
    at genericPrint (/Users/donovan/src/babel-codemod/node_modules/recast/lib/printer.js:164:9)
    at printRootGenerically (/Users/donovan/src/babel-codemod/node_modules/recast/lib/printer.js:105:15)
    at maybeReprint (/Users/donovan/src/babel-codemod/node_modules/recast/lib/printer.js:97:16)
1 file(s), 0 modified, 1 errors
```

**Comment by eventualbuddha** [comment]
Ah, looks like recast [does support `Noop`](https://github.com/benjamn/recast/blob/ccc6317a3fd8c4212b980db4e895ccdcf43c46f9/lib/printer.js#L241) and has since v0.10.14 (~2.5 years). I wonder why this is happening, then…

**Comment by MagicDuck** [comment]
Hmm, now that i look closer at it, according to the error stack, the error is thrown from ast-types, could it be that lib that does not support it? After all, that checking function looks fairly complex: https://github.com/benjamn/ast-types/blob/master/lib/types.js#L60 ...

**Comment by eventualbuddha** [comment]
Ah, it looks like `ast-types` defines `Noop` like so:

```
  def("Noop")
    .bases("Node")
    .build();
```

Notably, it does not have a base of `Statement`, so this part of `printer.js` will not match it as a `Comment` or a `Statement` and will assert that it is a string where it fails:

```
        if (namedTypes.Comment.check(stmt)) {
            // The pretty printer allows a dangling Comment node to act as
            // a Statement when the Comment can't be attached to any other
            // non-Comment node in the tree.
            sawComment = true;
        } else if (namedTypes.Statement.check(stmt)) {
            sawStatement = true;
        } else {
            // When the pretty printer encounters a string instead of an
            // AST node, it just prints the string. This behavior can be
            // useful for fine-grained formatting decisions like inserting
            // blank lines.
            isString.assert(stmt);
        }
```

My naïve fix would be to make `Noop` be the same as `EmptyStatement`:

```js
// The empty .build() here means that an EmptyStatement can be constructed
// (i.e. it's not abstract) but that it needs no arguments.
    def("EmptyStatement").bases("Statement").build();
```

Unfortunately, the [commit that adds `Noop` to babel](https://github.com/babel/babel/commit/8eee5367f3bac4348af99971150bf9d619455bd7) is pretty light on explanation. It seems to mostly be used as an alternative to `null` for type annotations.

@MagicDuck I think you could simply use `t.emptyStatement()` instead of `t.noop()` and get the behavior you're looking for.

**Comment by MagicDuck** [comment]
Ah thanks @eventualbuddha, that should be enough for  my needs. Much appreciate your time ! 😁

**Comment by eventualbuddha** [comment]
https://github.com/benjamn/ast-types/pull/245

**Comment by eventualbuddha** [comment]
Not really anything to do here, so closing.
