### ISSUE TITLE
Add option to transpile TypeScript plugins directly

### ISSUE THREAD

**Issue by eventualbuddha** [square/babel-codemod#51]
Probably should use ts-node the same way #31 uses babel-register, but will require some research since the options are obviously different. What should the option be called? `--ts-transpile`? Should we just put both `--babel-transpile` and this one under a single `--transpile-plugins` flag? Maybe it should even be on by default, as long as we’re already shipping the dependencies with the package.

cc @mcMickJuice

**Comment by mcMickJuice** [comment]
I think the `require('ts-node').register()` will work just fine. 

Regarding typescript transpilation by default:

* ts-node.register requires typescript module. If it's not locally installed the command will fail.  We could check for the existence of the typescript module before calling register
* I can see the argument for loading babel-preset-env and transpiling using babel by default. There is and will be js syntax that node doesn't yet support that users might wanna utilize. Typescript is a non-standard superset of javascript so I think that users should opt in. If we require opt in, we can better message them if they don't have typescript installed locally.  How would we do that if they wrote plugins in typescript but didn't have typescript installed locally? They'd get syntax errors and would blame this package 😄 

Just a couple of thoughts. I can still start down the path towards implementing this and accommodate whatever you decide you'd like to do.

**Comment by mcMickJuice** [comment]
started work on this here. https://github.com/mcMickJuice/babel-codemod/tree/feature/typescript-compile-plugins

**Comment by eventualbuddha** [comment]
Thanks! We can check that `typescript` is available and fail even before loading ts-node. And yeah, it should be opt-in.
