### ISSUE TITLE
Run prettier or eslint on files as a post-processing step

### ISSUE THREAD

**Issue by eventualbuddha** [square/babel-codemod#58]
I'm now convinced this would be a useful addition to core. How should we do it?

**Comment by mcMickJuice** [comment]
Can we reopen issue https://github.com/square/babel-codemod/issues/20 which has a discussion around this?

Personally, I believe that adding prettier, eslint or any other library for post-processing to this project's core is outside the scope of this tool.

I think [this comment](https://github.com/square/babel-codemod/issues/20#issuecomment-305571097) details the right approach.

**Comment by eventualbuddha** [comment]
Closing in favor of #20.
